# Generated by Django 4.1.1 on 2022-10-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Thrid Year'), (4, 'Fourth Year'), (5, 'Graduate Student'), (6, 'Other')], null=True),
        ),
    ]
