# Generated by Django 4.1.1 on 2022-11-10 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_course_department_alter_profile_major_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='home.department'),
        ),
    ]
