# Generated by Django 4.1.1 on 2022-10-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_email_profile_major_profile_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year',
        ),
    ]
