# Generated by Django 4.1.1 on 2022-10-23 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_followers_user_delete_profile_followers_another_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Thrid Year'), (4, 'Fourth Year'), (5, 'Graduate Student'), (6, 'Other')], null=True)),
                ('major', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='home.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
