# Generated by Django 4.1.1 on 2022-11-04 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_section_schedules_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='classes',
            field=models.ManyToManyField(null=True, related_name='schedules', to='home.section'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='home.profile'),
        ),
    ]
