# Generated by Django 4.1.1 on 2022-11-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_schedule_classes_alter_schedule_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='classes',
            field=models.ManyToManyField(related_name='schedules', to='home.section'),
        ),
    ]
