# Generated by Django 4.1.1 on 2022-10-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_profile_follows_profile_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='home.profile'),
        ),
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
